name: Solomon Etsecom Portfolio Webpage
on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:
    inputs:
      solomon-portfolio-webpage-setup:
        description: "Do You Want To Terraform Plan and Apply solomon Portfolio Webpage Setup on Aws (yes/no)"
        required: true
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"

env:
  AWS_ACCOUNT_NUMBER: 505648753038
  AWS_REGION: us-east-2
  TF_VAR_hcp_client_id: ${{secrets.HCP_CLIENT_ID}}
  TF_VAR_hcp_client_secret: ${{secrets.HCP_CLIENT_SECRET}}
permissions:
  id-token: write
  contents: read
  pull-requests: write
  

jobs:
  solomon-portfolio-webpage-setup-plan:
    name: Terraform Plan solomon Portfolio Webpage Setup on Aws
    if: >-
      (github.event_name == 'pull_request') || (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.solomon-portfolio-webpage-setup == 'yes')
    uses: ./.github/workflows/terraform_base_action.yml
      # ./.github/workflows/terraform-base.yml #Techsecom/terraform-gha-aws-oidc-config/.github/workflows/terraform-base.yml@main
    secrets: inherit
    with:
      stage: solomon-portfolio-webpage-setup
      iam_role: "arn:aws:iam::505648753038:role/terraform-gha-oidc-role"
      tf_mode: "plan"
      environment_directory: solomon_portfolio_webpage/
      project_name: techsecom-net
      org_domain_name: techsecom
      generate_ir: true
      deployment_time: 8
      deployment_status: "success"
      product_name: "solomon Portfolio Webpage Setup on Aws"
      deployment_cluster_name: "solomon-portfolio-webpage-setup-plan"
      aws_account_name: "techsecom-aws-oidc-account"
      code_commit_sha: ${{github.sha}}
      code_git_ref: ${{github.ref}}
      release_version: "v1.0.0"
      aws_region: "us-east-2"
      ir_s3_bucket: techsecom-rke2-manager-state

  solomon-portfolio-webpage-setup-apply:
    name: Terraform Apply solomon Portfolio Webpage Setup on Awsr
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.solomon-portfolio-webpage-setup== 'yes'
    uses: ./.github/workflows/terraform_base_action.yml
    needs: solomon-portfolio-webpage-setup-plan
    secrets: inherit
    with:
      stage: solomon-portfolio-webpage-setup
      iam_role: "arn:aws:iam::505648753038:role/terraform-gha-oidc-role"
      tf_mode: "apply"
      environment_directory: solomon_portfolio_webpage/
      project_name: techsecom-net
      org_domain_name: techsecom
      generate_ir: true
      deployment_time: 8
      deployment_status: "success"
      product_name: "solomon Portfolio Webpage Setup on Aws"
      deployment_cluster_name: "solomon-portfolio-webpage-setup-apply"
      aws_account_name: "techsecom-aws-oidc-account"
      code_commit_sha: ${{github.sha}}
      code_git_ref: ${{github.ref}}
      release_version: "v1.0.0"
      aws_region: "us-east-2"
      ir_s3_bucket: techsecom-rke2-manager-state
      
  